[package]
name = "rmpd-integrations"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
rmpd-core.workspace = true
rmpd-plugin.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
toml.workspace = true
